name: SignShop
main: org.wargamer2010.signshop.SignShop
version: 2.11.2
dev-url: http://dev.bukkit.org/server-mods/signshop
author: Wargamer2010 and Devinish
depend: [BKCommonLib, LangUtils]
softdepend: [Vault, Multiverse-Core, dynmap]
api-version: 1.13
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload|stats|version|about|help|sign|tutorial]
